TEST_CASES = [
    # --- TRONG DỮ LIỆU (CƠ BẢN) ---
    {
        "id": 1,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời gian thử việc tối đa đối với người lao động có trình độ đại học là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 2,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời gian thử việc tối đa của lao động có trình độ cao đẳng là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 3,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động được nghỉ bao nhiêu ngày phép năm nếu làm đủ 12 tháng trong điều kiện bình thường?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 4,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Lương thử việc tối thiểu bằng bao nhiêu phần trăm lương của công việc đó?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 5,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời giờ làm việc bình thường không quá bao nhiêu giờ trong một ngày và một tuần?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 6,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Làm thêm giờ vào ngày nghỉ hằng tuần được trả lương ít nhất bằng bao nhiêu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 7,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Làm thêm giờ vào ngày nghỉ lễ, tết, ngày nghỉ có hưởng lương được trả lương ít nhất bằng bao nhiêu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 8,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Có bao nhiêu loại hợp đồng lao động theo Bộ luật Lao động hiện hành?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 9,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời gian thử việc đối với công việc cần trình độ chuyên môn kỹ thuật trung cấp là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 10,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động làm việc vào ban đêm được trả thêm ít nhất bao nhiêu phần trăm tiền lương?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 11,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Lao động nữ mang thai từ tháng thứ mấy thì được giảm giờ làm việc hoặc chuyển công việc nhẹ hơn?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 12,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người sử dụng lao động có được giữ bản chính giấy tờ tùy thân, văn bằng, chứng chỉ của người lao động không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 13,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Tuổi nghỉ hưu của người lao động trong điều kiện lao động bình thường được quy định như thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 14,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động kết hôn được nghỉ bao nhiêu ngày và có được hưởng nguyên lương không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 15,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Bố đẻ hoặc mẹ đẻ chết thì người lao động được nghỉ bao nhiêu ngày hưởng nguyên lương?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 16,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Con kết hôn thì người lao động được nghỉ mấy ngày và có được hưởng lương không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 17,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời gian nghỉ thai sản của lao động nữ khi sinh con là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 18,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Khi vợ sinh con, lao động nam đang đóng bảo hiểm xã hội được nghỉ thai sản bao nhiêu ngày?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 19,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động làm việc bao lâu cho một người sử dụng lao động thì được tăng thêm 1 ngày phép năm?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 20,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Hợp đồng thử việc có bắt buộc phải đóng bảo hiểm xã hội không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 21,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người sử dụng lao động phải báo trước bao nhiêu ngày khi đơn phương chấm dứt hợp đồng lao động không xác định thời hạn?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 22,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Tiền lương trong thời gian nghỉ thai sản của người lao động do cơ quan nào chi trả?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 23,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động có được tạm ứng tiền lương khi gặp khó khăn không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 24,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Bộ luật Lao động quy định những hình thức xử lý kỷ luật lao động nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 25,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Có được áp dụng nhiều hình thức xử lý kỷ luật lao động đối với một hành vi vi phạm kỷ luật không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 26,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời hiệu xử lý kỷ luật lao động tối đa là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 27,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động bị tạm đình chỉ công việc trong những trường hợp nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 28,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Thời gian tạm đình chỉ công việc tối đa đối với người lao động là bao lâu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 29,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người lao động được nghỉ hưởng nguyên lương vào những ngày lễ, tết nào trong năm?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 30,
        "category": "Trong dữ liệu (Cơ bản)",
        "query": "Người sử dụng lao động có phải trả lương cho ngày nghỉ phép hằng năm chưa nghỉ hết không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    # --- TRONG DỮ LIỆU (NÂNG CAO) ---
    {
        "id": 31,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Cách tính trợ cấp thôi việc cho người lao động làm việc từ 5 năm trở lên?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 32,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Trường hợp nào người sử dụng lao động được đơn phương chấm dứt hợp đồng lao động mà không cần báo trước?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 33,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Trợ cấp mất việc làm được tính và chi trả cho người lao động như thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 34,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Lao động nữ nuôi con dưới 12 tháng tuổi được hưởng những quyền lợi gì về thời giờ làm việc và nghỉ ngơi?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 35,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Người lao động đơn phương chấm dứt hợp đồng lao động trái pháp luật thì phải bồi thường những khoản nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 36,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Doanh nghiệp có được quyền sa thải người lao động tự ý bỏ việc 5 ngày cộng dồn trong 30 ngày không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 37,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Quy trình xử lý kỷ luật sa thải người lao động cần tuân thủ những bước nào để hợp pháp?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 38,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Nếu doanh nghiệp đơn phương chấm dứt hợp đồng lao động trái pháp luật thì phải bồi thường những khoản nào cho người lao động?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 39,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Người lao động làm công việc nặng nhọc, độc hại, nguy hiểm được nghỉ bao nhiêu ngày phép năm?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 40,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Cách tính tiền lương làm thêm giờ vào ban đêm của ngày nghỉ lễ, tết thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 41,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Người sử dụng lao động có được tự ý khấu trừ lương của người lao động để bồi thường thiệt hại dụng cụ bị hư hỏng không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 42,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Hợp đồng lao động đương nhiên chấm dứt trong những trường hợp nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 43,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Khi chuyển người lao động sang làm công việc khác so với hợp đồng lao động, doanh nghiệp cần tuân thủ điều kiện gì?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 44,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Tiền lương của người lao động trong thời gian ngừng việc do lỗi của người sử dụng lao động được tính thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 45,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Tiền lương ngừng việc do sự cố điện, nước hoặc thiên tai, dịch bệnh được thỏa thuận như thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 46,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Doanh nghiệp có bắt buộc phải thưởng Tết hay lương tháng 13 cho người lao động không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 47,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Thỏa ước lao động tập thể là gì và khi nào nó chính thức có hiệu lực?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 48,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Trình tự, thủ tục giải quyết tranh chấp lao động cá nhân tại Hòa giải viên lao động diễn ra thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 49,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Người lao động nước ngoài làm việc tại Việt Nam bắt buộc phải có giấy phép lao động trong trường hợp nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 50,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Hợp đồng lao động bị coi là vô hiệu toàn bộ trong những trường hợp cụ thể nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 51,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Thẩm quyền tuyên bố hợp đồng lao động vô hiệu thuộc về cơ quan nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 52,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Tai nạn lao động được định nghĩa thế nào và doanh nghiệp phải bồi thường ra sao nếu có lỗi của người lao động?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 53,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Mức bồi thường tai nạn lao động của doanh nghiệp khi lỗi hoàn toàn thuộc về người sử dụng lao động?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 54,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Chi phí khám và điều trị tai nạn lao động cho người lao động do ai chi trả?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 55,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Doanh nghiệp có được ký hợp đồng lao động xác định thời hạn nhiều lần với người lao động cao tuổi không?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 56,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Khi nào người lao động có quyền từ chối làm thêm giờ mà không bị coi là vi phạm kỷ luật lao động?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 57,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Mức đóng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp bắt buộc của người lao động hiện nay là bao nhiêu?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 58,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Người lao động bị ốm đau dài ngày được hưởng chế độ bảo hiểm xã hội như thế nào?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 59,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Doanh nghiệp thay đổi cơ cấu, công nghệ ảnh hưởng đến việc làm của nhiều người lao động thì phải lập phương án gì?",
        "default_eval": "Pass (Không ảo giác)",
    },
    {
        "id": 60,
        "category": "Trong dữ liệu (Nâng cao)",
        "query": "Quyền lợi ưu tiên thanh toán của người lao động khi doanh nghiệp bị phá sản hoặc giải thể là gì?",
        "default_eval": "Pass (Không ảo giác)",
    },
    # --- NGOÀI DỮ LIỆU (OUT-OF-DOMAIN) ---
    {
        "id": 61,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Công thức tính lực hấp dẫn trong vật lý lượng tử là gì?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 62,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Cách nấu món phở bò truyền thống của Hà Nội ngon chuẩn vị?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 63,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Thủ đô của nước Úc là thành phố nào?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 64,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Làm sao để viết một chương trình Python kết nối với cơ sở dữ liệu MySQL?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 65,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Tác giả của cuốn tiểu thuyết nổi tiếng 'Số Đỏ' là ai?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 66,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Giải thích thuyết tương đối rộng của Albert Einstein một cách dễ hiểu?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 67,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Làm thế nào để tự học đàn guitar tại nhà hiệu quả cho người mới bắt đầu?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 68,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Các bước để đăng ký tài khoản quảng cáo trên Facebook Business?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 69,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Tác động của biến đổi khí hậu đối với rạn san hô Great Barrier như thế nào?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 70,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Điện thoại iPhone đầu tiên được Apple ra mắt vào năm nào?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 71,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Hệ mặt trời của chúng ta có bao nhiêu hành tinh và tên của chúng?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 72,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Cách điều trị bệnh cảm cúm thông thường tại nhà an toàn?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 73,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Làm sao để chụp ảnh phong cảnh đẹp bằng điện thoại di động?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 74,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Lịch sử hình thành và phát triển của mạng Internet toàn cầu?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    {
        "id": 75,
        "category": "Ngoài dữ liệu (Out-of-domain)",
        "query": "Những địa điểm du lịch nổi tiếng nhất không thể bỏ qua ở Đà Nẵng?",
        "default_eval": "Pass (Chống ảo giác tốt)",
    },
    # --- CÂU HỎI ĐÁNH LỪA (DECEPTIVE) ---
    {
        "id": 76,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Theo luật mới, sinh viên đi làm thêm không cần đóng thuế thu nhập cá nhân đúng không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 77,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Tôi nghe nói luật mới cấm hoàn toàn việc thử việc đối với tất cả các ngành nghề đúng không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 78,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Tại sao Bộ luật Lao động lại quy định người lao động tự ý nghỉ việc phải bồi thường cho công ty 100 tháng lương?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 79,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Có đúng là doanh nghiệp không được phép sa thải nhân viên dù họ tự ý nghỉ việc bao nhiêu ngày đi nữa?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 80,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Luật lao động mới có quy định tăng số ngày nghỉ phép năm tối thiểu từ 12 ngày lên 50 ngày không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 81,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Vì sao người lao động thử việc lại được trả lương gấp đôi lương chính thức theo quy định của pháp luật?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 82,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Nghe nói người đi làm vào ngày Tết được trả lương gấp 10 lần ngày thường, điều này quy định ở điều mấy?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 83,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Tại sao luật lại bắt buộc nhân viên nam nghỉ thai sản 6 tháng giống như nhân viên nữ khi vợ sinh con?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 84,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Có đúng là người sử dụng lao động có quyền thu giữ chứng minh nhân dân của nhân viên để làm tin không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 85,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Tôi nghe nói hợp đồng lao động bằng lời nói luôn có giá trị cao hơn hợp đồng bằng văn bản, đúng không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 86,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Có phải người lao động dưới 18 tuổi thì hoàn toàn không được phép đi làm bất kỳ công việc nào?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 87,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Có đúng là tiền lương thử việc chỉ được trả tối đa 10% lương chính thức của công việc đó không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 88,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Tại sao luật quy định doanh nghiệp phải trả lương bằng đô la Mỹ (USD) cho người lao động Việt Nam?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 89,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Nghe nói người lao động đơn phương chấm dứt hợp đồng đúng luật vẫn phải nộp phạt cho công ty, đúng không?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    {
        "id": 90,
        "category": "Câu hỏi đánh lừa (Deceptive)",
        "query": "Có đúng là người thử việc không cần phải tuân thủ nội quy lao động của doanh nghiệp?",
        "default_eval": "Pass (Đính chính chính xác)",
    },
    # --- TRUY VẤN MẬP MỜ (AMBIGUOUS) ---
    {
        "id": 91,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Làm sao để đăng ký cái đó?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 92,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Cái đó được tính như thế nào?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 93,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Quy định về thời gian nghỉ?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 94,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Tôi phải làm gì khi bị phạt?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 95,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Khi nào thì được nhận tiền đó?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 96,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Thủ tục nghỉ việc thế nào?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 97,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Làm sao để được giảm giờ làm?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 98,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Công ty có được làm thế không?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 99,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Ký cái hợp đồng đó ở đâu?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
    {
        "id": 100,
        "category": "Truy vấn mập mờ (Ambiguous)",
        "query": "Nghỉ thai sản thì thế nào?",
        "default_eval": "Pass (Yêu cầu làm rõ)",
    },
]
